### ISSUE TITLE
Problem with MikTeX installation of meta-class

### ISSUE THREAD

**Issue by erikvn** [AndyClifton/AccessibleMetaClass#3] opened 2016-10-05 19:30 UTC
I have tried to download your AccessibilityMeta project and tried to install it in my MikTex installation.
Sadly it doesn't work.
I have with succes installed the accessibility.sty file and put % in start of line 131 as you suggest.
When I start my tex document with
\documentclass[memoir,tagged]{meta} 

I get a Error on meta.cls can’t be found.

Can you supply me with some suggestions on installing your class?

**Comment by AndyClifton** [comment] 2017-03-16 19:58
Can't reproduce, sorry. Do you have `meta.cls` in the same directory?

**Comment by AndyClifton** [comment] 2017-12-01 21:56
Closing as cannot reproduce.

**Closed by AndyClifton** 2017-12-01 21:56 UTC
